### ISSUE TITLE
Add Monkey shaped background to QR code

### ISSUE THREAD

**Issue by sebrock** [sebrock/banano-donate#14]
Like this:
![image](https://user-images.githubusercontent.com/156824/88288916-ba6ccb00-ccf4-11ea-8595-4b86e1cfba22.png)

API by Otomanis 

`https://banano.id/pay/api.php?wallet=ban_1y154e15t7ih56zs195hfb6jcf7n5xerop35o9r4cm8o8tgtfe8r4hj4y4ji`

posted on Discord [here https://discordapp.com/channels/710222836660437045/733457871156543528/735525093316362442](https://discord.com/channels/710222836660437045/733457871156543528/735525093316362442)

**Comment by andrecrjr** [comment]
nice!

**Comment by andrecrjr** [comment]
there is a problem with discord link, i couldnt access it :'/

**Comment by sebrock** [comment]
> there is a problem with discord link, i couldnt access it :'/

oops.. try this:
[https://discord.com/channels/710222836660437045/733457871156543528/735525093316362442](https://discord.com/channels/710222836660437045/733457871156543528/735525093316362442)

**Comment by andrecrjr** [comment]
> > there is a problem with discord link, i couldnt access it :'/
> 
> oops.. try this:
> https://discord.com/channels/710222836660437045/733457871156543528/735525093316362442

it's closed to me :'/

**Comment by sebrock** [comment]
> > > there is a problem with discord link, i couldnt access it :'/
> 
> > 
> 
> > oops.. try this:
> 
> > https://discord.com/channels/710222836660437045/733457871156543528/735525093316362442
> 
> 
> 
> it's closed to me :'/

I see you are in the Banano.id channel. Exactly the right place. The link was to that stuff.

**Comment by andrecrjr** [comment]
done it's in the new branch feature/refactoring-react!

**Comment by sebrock** [comment]
Very nice!
Function: yes
Placement: need to think of something else for the format of the entire screen.
Closing issue regardless.

![image](https://user-images.githubusercontent.com/156824/90597250-ff4f2900-e1f0-11ea-896c-5e17a8b2f8bd.png)
