### ISSUE TITLE
Deploy languages

### ISSUE THREAD

**Issue by sebrock** [sebrock/banano-donate#7]
- [x] **Phase 1 - alpha** #11 

- [x] **Phase 2 - beta** #12 

- [x] **Phase 3 - V1.0.0.** #13

**Comment by sebrock** [comment]
- Moved Japanese to Phase 1
- Deleted Finnish and Romanian

**Comment by sebrock** [comment]
- Deleted Greek

**Comment by HakaCode** [comment]
can i try to translate for pt_BR -Portuguese (Brazil) ?

**Comment by sebrock** [comment]
> can i try to translate for pt_BR -Portuguese (Brazil) ?

Thanks for the offer, but we have two translators for pr_BR already, #4 
All translations but one have been done already, as you can see here: #5
